### ISSUE TITLE
Mono returns null instead of empty for 204 status code

### ISSUE THREAD

**Issue by RaviH** [JakeWharton/retrofit2-reactor-adapter#15]
Hello,

This could be a bug or a question, I am not sure which.

---
When I get a 204 response from the http server, Mono is currently returning a `null` instead of being `empty`. As far as I understand Mono it is 0 or 1 element in it. But, I could be wrong.

To recreate, I added this method to your `MonoTest` and it passes:

```
  @Test public void bodySuccess204() {
    server.enqueue(new MockResponse().setResponseCode(204));

    RecordingSubscriber<String> subscriber = subscriberRule.create();
    service.body().subscribe(subscriber);
    subscriber.assertValue(null).assertComplete();
  }
```
---
The question then is:

1. Shouldn't Mono be empty instead of null, since 204 indicates no content / empty?
2. If so, then returning null is a bug possibly?

**Comment by JakeWharton** [comment]
This is a known unfortunate behavior. See https://github.com/square/retrofit/issues/2867 for the desire to avoid this. Right now it's not clear what the best course of action is given the generic `Converter` interface rather than something direct for request and response body types for proper intercepting.

I'm going to close since this is a systemic problem, not something specific to this converter.

**Comment by RaviH** [comment]
Thanks for the response @JakeWharton 

--
Just trying to understand the issue better. I read through https://github.com/square/retrofit/issues/2867 and also this: https://github.com/square/retrofit/pull/3003

Couple questions:

a. Is there a clean way to handle this in my code via converter / interceptor?
b. Based on https://github.com/square/retrofit/pull/3003 seems like this is fixed for RxJava. If it can be fixed for RxJava, can't we not import the same change to this converter?

**Comment by JakeWharton** [comment]
That linked PR is not merged because I'm not satisfied with how it works.
This should not need special handling in every call adapter because it has
nothing to do with call adapters, it's a problem with Converters. I'm
hoping to leverage Java 8 default methods to allow a Converter to handle
204/205, but it's a bit weird because we use the same type for request and
response converters.
